### ISSUE TITLE
Upgrade container pennylane lightning.gpu version to v0.24

### ISSUE THREAD

**Issue by duanyh12** [aws/amazon-braket-containers#50]
**Describe the feature you'd like**
An issue with v0.23 pennylane lightning.gpu on QAOA use cases has been detected (https://github.com/PennyLaneAI/pennylane/issues/2745). The bug will be addressed in the incoming lightning.gpu v0.24 release on June 21. As QAOA is an important use case for Braket, do Braket consider it necessary to update the containers correspondingly?

**How would this feature be used? Please describe.**
With the proposed upgrade, users will be able to run QAOA simulations with lightning.gpu embedded simulator with out-of-the-box containers.

**Describe alternatives you've considered**
Need to confirm if `os.system("pip install git+https://github.com/PennyLaneAI/pennylane-lightning-gpu.git@main")` in the job script can serve as a workaround.

**Additional context**

**Comment by duanyh12** [comment]
Confirming `os.system("pip install git+https://github.com/PennyLaneAI/pennylane-lightning-gpu.git@main")` will not work in the current PL_TORCH container. Might want to revisit it again after tomorrow's v0.24 launch.

**Comment by duanyh12** [comment]
PennyLane v0.24 has released. A quick workaround to resolve the issue is to add the following three lines at the beginning of a job script:
```python
import subprocess
subprocess.run(["pip", "install", "pennylane==0.24.0", "-q"])
subprocess.run(["pip", "install", "pennylane-lightning-gpu==0.24.0", "-q"])
```

**Comment by mlxd** [comment]
Hi @duanyh12 I recommend using
```python
import subprocess
subprocess.run(["pip", "install", "pennylane==0.24.0", "-q"])
subprocess.run(["pip", "install", "pennylane-lightning[gpu]==0.24.0", "-q"])
```

to ensure the GPU install goes through the Lightning CPU installer. It should be the same package installation now, but we expect those repos to eventually merge, and the paths to resolve via the same route.

**Comment by ajberdy** [comment]
As of https://github.com/aws/amazon-braket-containers/pull/59, we have upgraded PennyLane and are now using pennylane-lightning[gpu]==0.25.1
